config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: 'users'
  devise_for :property_owners, path: 'property_owners'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :properties, only: [:show, :new, :create] do
    collection do
      get 'my_properties'
    end
    resources :property_reservations, only: [:create, :show], shallow: true
  end
  resources :property_types, only: [:show, :new, :create]
  resources :property_regions, only: [:show, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :property_type
    belongs_to :property_region
    belongs_to :property_owner
    has_many :property_reservations, dependent: :destroy
    
    validates :title, :description, presence: true
    validates :rooms, :bathrooms, numericality: {message: "deve ser um número inteiro", only_integer: true}
    validates :rooms, :bathrooms, :daily_rate, numericality: {greater_than: 0}
end

app/models/property_owner.rb
class PropertyOwner < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  has_many :properties
end

app/models/property_region.rb
class PropertyRegion < ApplicationRecord
    has_many :properties
    
    validates :name, uniqueness: {message: 'já está cadastrada'}
    validates :name, presence: true
end

app/models/property_reservation.rb
class PropertyReservation < ApplicationRecord
  belongs_to :property
  belongs_to :user

  before_save :calculate_total_value
  
  private
  
  def calculate_total_value
    self.total_value = (end_date - start_date) * property.daily_rate
  end
end

app/models/property_type.rb
class PropertyType < ApplicationRecord
    has_many :properties
    
    validates :name, uniqueness: {message: 'já está cadastrado'}
    validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :property_reservations
  has_many :properties, through: :property_reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @properties = Property.all
        @property_types = PropertyType.all
        @property_regions = PropertyRegion.all
    end
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
    before_action :authenticate_property_owner!, only: [:new, :create]
    def show
        @property = Property.find(params[:id])
        @property_reservation = PropertyReservation.new
    end

    def new
        @property = Property.new
        @property_types = PropertyType.all
        @property_regions = PropertyRegion.all
    end

    def create
        @property_types = PropertyType.all
        @property_regions = PropertyRegion.all
        @property = Property.new(params.require(:property).permit(:title, :description,
                               :rooms, :bathrooms, :pets, :parking_slot, :daily_rate, 
                               :property_type_id, :property_region_id))
        @property.property_owner = current_property_owner
        if @property.save
            redirect_to @property
        else
            render :new
        end
    end

    def my_properties
        @properties = current_property_owner.properties
    end
end

app/controllers/property_regions_controller.rb
class PropertyRegionsController < ApplicationController
    def new
        @property_region = PropertyRegion.new
    end

    def create
        @property_region = PropertyRegion.new(params.require(:property_region).permit(:name))
        if @property_region.save
            redirect_to new_property_path
        else
            render :new
        end       
    end

    def show
        @property_region = PropertyRegion.find(params[:id])
        @properties = @property_region.properties.all
    end
end

app/controllers/property_reservations_controller.rb
class PropertyReservationsController < ApplicationController
    def create
        @property_reservation = current_user.property_reservations.new(property_reservation_params)
        @property_reservation.property = Property.find(params[:property_id])
        @property_reservation.save!

        redirect_to @property_reservation, notice: t('.success')
    end

    def show
        @property_reservation = PropertyReservation.find(params[:id])
    end

    def property_reservation_params
        params.require(:property_reservation).permit(:start_date, :end_date, :guests_integer)
    end
end

app/controllers/property_types_controller.rb
class PropertyTypesController < ApplicationController
    def new
        @property_type = PropertyType.new
    end

    def create
        @property_type = PropertyType.new(params.require(:property_type).permit(:name))
        if @property_type.save
            redirect_to new_property_path
        else
            render :new
        end
    end

    def show
        @property_type = PropertyType.find(params[:id])
        @properties = @property_type.properties.all
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<header>
    <h1> Flats </h1>
    <h3> Boas vindas ao sistema de locação de apartamentos </h3>
    <div>=================================================================</div>
</header>

<aside>
    <h3> Filtrar os imóveis disponíveis por tipo:</h3>
    <nav>
        <% @property_types.each do |pt| %>
            <%= link_to pt.name, property_type_path(pt) %>
        <% end %>
        <div>=================================================================</div>
    </nav>
    <h3> Filtrar os imóveis disponíveis por região:</h3>
    <nav>
        <% @property_regions.each do |pr| %>
            <%= link_to pr.name, property_region_path(pr) %>
        <% end %>
        <div>=================================================================</div>
    </nav>
</aside>

<%= render "shared/property_preview" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flats</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav>
      <% if property_owner_signed_in? %> 
          <%= current_property_owner.email %></li> ||
          <%= link_to('Cadastre seu imóvel aqui', new_property_path)%> ||
          <%= link_to('Meus imóveis', my_properties_properties_path)%> ||
          <%= link_to 'Sair', destroy_property_owner_session_path, method: :delete %> 
        <div>=================================================================</div>
      <% elsif user_signed_in? %>
          <%= current_user.email %> ||
          <%= link_to 'Sair', destroy_user_session_path, method: :delete %> 
      <% else %>
        <p><%= link_to 'Entrar como proprietário', new_property_owner_session_path %> || 
        <%= link_to 'Entrar como usuário', new_user_session_path %></p>
      <% end %>
      <%= %>
    </nav>
    <p> <%= notice %> </p>
    <p> <%= alert %> </p>
    <%= yield %>
  </body>
</html>

app/views/properties/my_properties.html.erb
<h1>Meus imóveis</h1>

<%= render 'shared/property_preview' %>

app/views/properties/new.html.erb
<h1> Cadastro de Imóvel </h1>

<div>
================================================================================
</div>

<p> Lista de Regiões atualmente cadastradas. <%= link_to 'Caso precise adicionar
 uma nova região, clique aqui', new_property_region_path %><p>
<% if @property_regions.any? %>
    <% @property_regions.each do |region| %>
        <li><%= region.name%></li>
    <% end %>
<% else %>
    <p> Nenhuma região atualmente cadastrada </p>
<% end %>
<div>
================================================================================
</div>

<p> Lista de tipos de imóveis atualmente cadastrados. <%= link_to 'Caso precise adicionar
 um novo tipo, clique aqui', new_property_type_path %><p>
<% if @property_types.any? %>
    <% @property_types.each do |type| %>
        <li><%= type.name%></li>
    <% end %>
<% else %>
    <p> Nenhum tipo atualmente cadastrado </p>
<% end %>
<div>
================================================================================
</div>

<p> Preencha no formulário abaixo os dados do imóvel que deseja cadastrar.
    Todos os campos devem ser preenchidos! </p>
    
<%= form_with model: @property do |f| %>

<div>
    <%= f.label :title %>
    <%= f.text_field :title %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:title).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :description, "Descrição do imóvel"%>
    <%= f.text_field :description %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:description).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :rooms%>
    <%= f.text_field :rooms %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:rooms).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :bathrooms%>
    <%= f.text_field :bathrooms %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:bathrooms).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :daily_rate%>
    <%= f.text_field :daily_rate %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:daily_rate).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :property_type_id, 'Tipo' %>
    <%= f.collection_select :property_type_id, @property_types, :id, :name, prompt: 'Escolha um tipo' %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:property_type).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :property_region_id, 'Região' %>
    <%= f.collection_select :property_region_id, @property_regions, :id, :name, prompt: 'Escolha uma região' %>
    <li><FONT COLOR="#ff0000"><%= @property.errors.full_messages_for(:property_region).to_sentence if (not @property.nil?) and (@property.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.label :parking_slot %>
    <%= f.check_box :parking_slot %>
</div>

<div>
    <%= f.label :pets %>
    <%= f.check_box :pets %>
</div>
<div>
    <%= f.submit "Finalizar cadastro" %>
</div>

<% end %>

app/views/properties/show.html.erb
<h1><%= @property.title %></h1>

<h3><%= @property.description %></h3>
<div>
<dl>
  <dt>Tipo:</dt>
  <dd><%= @property.property_type.name %></dd>

  <dt>Região:</dt>
  <dd><%= @property.property_region.name %></dd>
  
  <dt>Número de quartos:</dt>
  <dd><%= @property.rooms %></dd>

  <dt>Número de banheiros:</dt>
  <dd><%= @property.bathrooms %></dd>
  
  <dt>Aceita pets?</dt>
  <dd><%= if @property.pets then "Sim" else "Não" end %></dd>

  <dt>Vaga de estacionamento?</dt>
  <dd><%= if @property.parking_slot then "Sim" else "Não" end %></dt>

  <dt>Preço da diária:</dt>
  <dd><%= number_to_currency(@property.daily_rate) %></dd>

  <dt>Imóvel de:</dt>
  <dd><%= @property.property_owner.email %></dd>

</dl>
</div>

<h3> Verificar datas </h3>
<%= form_with model: [@property, @property_reservation] do |form|%>
  <%= form.label :start_date, 'Data de início'%>
  <%= form.date_field :start_date%>

  <%= form.label :end_date, 'Data de término'%>
  <%= form.date_field :end_date%>

  <%= form.label :guests_integer, 'Quantidade de pessoas'%>
  <%= form.number_field :guests_integer, step: 1, min: 1%>

  <%= form.submit 'Enviar reserva'%>
<% end %>

<%= link_to('Voltar', root_path)%>

app/views/property_owners/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/property_owners/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Se cadastre aqui", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/property_regions/new.html.erb
<h1> Cadastro de nova região </h1>
<p> Lembre-se que não pode deixar o espaço em branco e nem colocar uma região já existente </p>

<%= form_with model: @property_region do |f| %>

<div>
    <%= f.label :name, "Região"%>
    <%= f.text_field :name %>
    <li><FONT COLOR="#ff0000"><%= @property_region.errors.full_messages_for(:name).to_sentence if (not @property_region.nil?) and (@property_region.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.submit "Voltar ao cadastro" %>
</div>

<% end %>

app/views/property_regions/show.html.erb
<h1> Imóveis em <%= @property_region.name%></h1>

<%= render "shared/property_preview" %> 

app/views/property_reservations/show.html.erb
<h3> Reserva do imóvel <%= @property_reservation.property.title %> </h3>

<dl>
    <dt> Data de início:</dt>
    <dd> <%= l @property_reservation.start_date %> </dd>

    <dt> Data de término:</dt>
    <dd> <%= l @property_reservation.end_date %> </dd>

    <dt> Quantidade de pessoas:</dt>
    <dd> <%= @property_reservation.guests_integer %> </dd>

    <dt> Valor total:</dt>
    <dd> <%= number_to_currency(@property_reservation.total_value) %> </dd>
</dl>

app/views/property_types/new.html.erb
<h1> Cadastro de novo tipo de imóvel </h1>
<p> Lembre-se que não pode deixar o espaço em branco e nem colocar um tipo já existente </p>

<%= form_with model: @property_type do |f| %>

<div>
    <%= f.label :name, "Tipo"%>
    <%= f.text_field :name %>
    <li><FONT COLOR="#ff0000"><%= @property_type.errors.full_messages_for(:name).to_sentence if (not @property_type.nil?) and (@property_type.errors.any?) %></li></FONT>
</div>

<div>
    <%= f.submit "Voltar ao cadastro" %>
</div>
<%end%>

app/views/property_types/show.html.erb
<h1> Imóveis do tipo <%= @property_type.name%></h1>

<%= render "shared/property_preview" %> 

app/views/shared/_property_preview.html.erb
<section>
    <div><%= "Nenhum imóvel cadastrado," if not @properties.any?%>
    <%= link_to 'clique aqui para cadastrar um imóvel', new_property_path %>
    </div>

    <% @properties.each do |p| %>
        <div><%= link_to p.title, property_path(p.id) %></div>
        <div><%= p.description %></div>
        <div>Número de quartos: <%= p.rooms %></div>
        <div>=================================================================</div>
    <% end %>
</section>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Entrar", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Se cadastre aqui", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Esqueceu sua senha?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>